### ISSUE TITLE
cannot load stylesheets

### ISSUE THREAD

**Issue by ChristopherJTrent** [Studiosity/grover#260]
I don't have a rails app or anything fancy going on. 
All I'm trying to do is get a plain HTML file, that links to a CSS file, to render to a jpeg. 

No matter what I do, up to and including giving an absolute path using the `file://` protocol, my stylesheets *never* apply to the output. 

Below are the entire contents of my project. These three files should, in my opinion, be all the code I should have to write in order to get a basic jpeg image out the other side, but no, this doesn't apply card_template.css

Edit for clarification: the html file works perfectly fine in normal Chrome, Microsoft Edge, and Firefox. It's just Grover that can't handle it.

renderer.rb
```ruby
require "grover"

template = File.read('./template/card_template.html')


File.write(
    './out.jpg',
    Grover.new(template).to_jpeg
)
```
card_template.html
```html
<html>
    <head>
        <link rel="stylesheet" href="file:///C:/Users/Chris/source/ruby/MechaZooCardCreator/template/card_template.css" />
    </head>
    <body>
        <div id="card-frame-outer">
            <div id="card-image-container">
                <img />
            </div>
            <div id="card-frame-inner">
                <div id="energy-frame">
                    <p>0</p>
                </div>
                <div id="cardname-box">
                    <p>Cowboy for Game</p>
                </div>
                <div id="scrap-value-box">
                    <p>3</p>
                </div>
                <div id="card-type-box-back">
                    <div id="card-type-box-front">
                        <p id="card-type-text">!</p>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
```

card_template.css
```css
body {
    width: 756px;
    height: 1056px;
    margin: 0;
    font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
    font-weight: 900;
    text-rendering: geometricPrecision;
}
#card-frame-outer {
    background-color: black;
    width: 756px;
    height: 1056px;
    border-radius: 36px;
    z-index: 256;
}
#card-frame-inner {
    background-color: green;
    position: absolute;
    top: 36px;
    left: 36px;
    width: 684px;
    height: 984px;
    border-radius: 18px;
    z-index: 0;
}

#card-image-container {
    z-index: 1;
}

#energy-frame {
    border-radius: 36px 0px;
    background-color: white;
    border: 12px solid black;
    position: fixed;
    top: 24px;
    left: 24px;
    width: 162px;
    height: 210px;
    & > p {
        text-align: center;
        vertical-align: middle;
        line-height: 210px;
        font-size: 140px;
        height:inherit;
        width: inherit;
        margin: 0
    }
}

#cardname-box {
    position: fixed;
    top: 60px;
    left: 212px;
    width: 396px;
    & > p {
        width: 100%;
        text-align: center;
        font-size: 48px;
        margin: 0;
        --o-offset: 2px;
        --o-off-neg: calc(var(--o-offset) * -1);
        --o-color: #FFF;
        text-shadow: 
            var(--o-off-neg) var(--o-off-neg) 0 var(--o-color), 
            var(--o-offset) var(--o-off-neg) 0 var(--o-color), 
            var(--o-off-neg) var(--o-offset) 0 var(--o-color), 
            var(--o-offset) var(--o-offset) 0 var(--o-color);
    }
}

#scrap-value-box {
    position: fixed;
    height: 93px;
    width: 93px;
    border-radius: 93px;
    border: 6px solid black;
    background-color: white;
    left: 603px;
    top: 48px;
    & > p {
        width: 93px;
        line-height: 93px;
        text-align: center;
        margin: 0;
        font-size: 46px;
    }
}
```
