### ISSUE TITLE
Option to change absolute path (perhaps, only in container context)

### ISSUE THREAD

**Issue by rafaeldev** [Studiosity/grover#283]
Hi everyone!

I'm using Grover in a docker context where a container is running rails (called web) and another container is running chrome (called pdf)

When I render an image, for example, which brings my `asset_host` value in the asset path:
`<img src="http://localhost:3000/assets/insert-your-logo-e3833ddb.png" />`

To _workaround_ it, I replace `http://localhost:3000` with a host containerized name, in this case, `http://web:3000`

Is it good to consider replacing the absolute host by configuration?

Below, the main points of by code:

`docker-compose.yml`
```yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: bash -c "./bin/dev"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    stdin_open: true
    tty: true

  pdf:
    image: browserless/chrome:latest
    ports:
      - "3001:3000"
    restart: always
    environment:
      LOG_LEVEL: info
      MAX_CONCURRENT_SESSIONS: 1
      PREBOOT_CHROME: "true"
      CHROME_FLAGS: >
        --no-sandbox 
        --disable-setuid-sandbox 
        --disable-dev-shm-usage 
        --disable-gpu 
        --no-first-run 
        --disable-sync
        --disable-features=HttpsUpgrades
```

`initializers/grover.rb`
```ruby
# frozen_string_literal: true

Grover.configure do |config|
  app_url = ENV.fetch("APP_URL", "http://web:3000")
  options = {
    format: "A4",
    print_background: true,
    margin: { top: "5mm", bottom: "5mm" },
    browser_ws_endpoint: ENV.fetch("BROWSER_WS_ENDPOINT", "ws://pdf:3000"),
    display_url: app_url,
    skip_chromium_download: true,
    puppeteer: {
      args: %w[
        --no-sandbox
        --disable-setuid-sandbox
      ]
    }
  }

  Rails.logger.info "INITIALIZING GROVER WITH OPTIONS: #{options}"

  config.options = options
  config.root_url = app_url
end
```

I created a method (inside `ApplicationController`) to reuse in controllers which render pdf files:
```ruby
def render_to_pdf(options)
    filename = options.delete(:filename)
    html = render_to_string(**options)
    html = html.gsub("http://localhost:3000", "http://web:3000") # <-- POINT WHERE DO THE REPLACE

    puts "html: #{html}"

    send_data Grover.new(html).to_pdf,
              filename: filename,
              type: "application/pdf",
              disposition: "inline"
  end
```

Thanks!
